# Generated by Django 5.1.1 on 2024-09-12 21:31

import core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель мебели')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подтип мебели')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип мебели')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет мебели')),
                ('hex_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате HEX (#RRGGBB или #RGB).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='HEX код цвета')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='catalog.furnituremodel', verbose_name='Модель мебели')),
            ],
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.furnituresubtype', verbose_name='Подтип мебели'),
        ),
        migrations.AddField(
            model_name='furnituresubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='catalog.furnituretype', verbose_name='Тип мебели'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.set_furniture_image_filename, verbose_name='Фото')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.color', verbose_name='Цвет')),
            ],
        ),
    ]
