# Generated by Django 5.1.1 on 2024-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Цвет мебели', 'verbose_name_plural': '....Цвета мебели'},
        ),
        migrations.AlterModelOptions(
            name='furnituremodel',
            options={'ordering': ['name'], 'verbose_name': 'Модель мебели', 'verbose_name_plural': '...Модели мебели'},
        ),
        migrations.AlterModelOptions(
            name='furnituresubtype',
            options={'ordering': ['name'], 'verbose_name': 'Подтип мебели', 'verbose_name_plural': '..Подтипы мебели'},
        ),
        migrations.AlterModelOptions(
            name='furnituretype',
            options={'ordering': ['name'], 'verbose_name': 'Тип мебели', 'verbose_name_plural': '.Типы мебели'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фото мебели', 'verbose_name_plural': '.....Фото мебели'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='images',
            field=models.ManyToManyField(related_name='colors', to='catalog.image', verbose_name='Фото'),
        ),
    ]
