# Generated by Django 5.1.1 on 2024-09-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_color_options_alter_furnituresubtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Цвет мебели', 'verbose_name_plural': 'Цвета мебели'},
        ),
        migrations.AlterModelOptions(
            name='furnituremodel',
            options={'ordering': ['name'], 'verbose_name': 'Модель мебели', 'verbose_name_plural': 'Модели мебели'},
        ),
        migrations.AlterModelOptions(
            name='furnituresubtype',
            options={'ordering': ['name'], 'verbose_name': 'Подтип мебели', 'verbose_name_plural': 'Подтипы мебели'},
        ),
        migrations.AlterModelOptions(
            name='furnituretype',
            options={'ordering': ['name'], 'verbose_name': 'Тип мебели', 'verbose_name_plural': 'Типы мебели'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фото мебели', 'verbose_name_plural': 'Фото мебели'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='images',
        ),
        migrations.RemoveField(
            model_name='color',
            name='model',
        ),
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='image',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.furnituremodel', verbose_name='Модель мебели'),
        ),
    ]
