# Generated by Django 5.1.1 on 2024-09-13 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_image_description_alter_color_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituremodel',
            name='subtype',
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.furnituretype', verbose_name='Тип мебели'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FurnitureSubType',
        ),
    ]
