# Generated by Django 5.1.1 on 2024-09-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_image_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='model',
        ),
        migrations.AddField(
            model_name='color',
            name='models',
            field=models.ManyToManyField(related_name='colors', to='catalog.furnituremodel'),
        ),
        migrations.AddField(
            model_name='image',
            name='furniture_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.furnituremodel'),
        ),
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.color'),
        ),
    ]
