# Generated by Django 5.1.1 on 2024-09-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_image_model_color_models_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['hex_code'], 'verbose_name': 'Цвет мебели', 'verbose_name_plural': 'Цвета мебели'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='models',
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='colors',
            field=models.ManyToManyField(related_name='furniture_models', to='catalog.color'),
        ),
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='image',
            name='furniture_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.furnituremodel', verbose_name='Модель мебели'),
        ),
    ]
