# Generated by Django 5.1.1 on 2024-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_color_options_remove_color_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='colors',
            field=models.ManyToManyField(related_name='furniture_models', to='catalog.color', verbose_name='Цвет'),
        ),
    ]
