# Generated by Django 5.1.1 on 2024-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_furnituremodel_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='colors',
            field=models.ManyToManyField(related_name='furniture_models', to='catalog.color', verbose_name='цвета мебели'),
        ),
    ]
