# Generated by Django 5.1.1 on 2024-09-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['furniture_model', 'color', 'uploaded_at'], 'verbose_name': 'Фото мебели', 'verbose_name_plural': 'Фото мебели'},
        ),
    ]
